#!/bin/bash

ENV_LOC="$1";
shift;

function upgrade_deps() {
    uv pip install -U pylint ipdb python-lsp-server python-lsp-ruff black ropevim pip-tools pynvim pylsp-mypy ruff
}

if [ ! -z "$VIRTUAL_ENV" ]; then
    echo "Already inside of venv. Only upgrading deps"
    upgrade_deps
    exit 0;
fi

if [ -f activate ]; then
    echo "activate already exists, activate env to install packages. exit"
    exit 1;
fi

if [ -z $ENV_LOC ]; then
    echo "provide path to env or activate existing"
    exit 1;
fi

NAME=$(basename $(realpath "$ENV_LOC"))
uv venv --prompt="uv-$NAME" "$ENV_LOC"
ln -s $ENV_LOC/bin/activate .
. activate
upgrade_deps
