#!/bin/bash

repo="$1"
reg="$2"
name="$3"

url_tag=' | .browser_download_url'

if [ "$name" = "-n" ]; then
    url_tag=" | .name"
fi

curl -L -s https://api.github.com/repos/$repo/releases/latest | jq '.assets[] | select(.name |  test("'"$reg"'"; "i") ) '"$url_tag" -r
