#!/usr/bin/env python

import sys
import requests


def main(input_file):
    with open(input_file, "r", encoding="utf-8") as fin:
        text = fin.read()
    req = requests.post("https://api.github.com/markdown",
                        json={"text": text, "mode": "markdown"})
    print(req.text)


if __name__ == "__main__":
    main(sys.argv[1])
