#!/bin/bash

USERNAME="$1"
SITE="$2"
CMD="$3"

askpass() {
    printf "%s" "password=";
    echo $(python3 -c "import getpass; print(getpass.getpass())" | spectre -Fnone -u"$USERNAME" "$SITE");
}; 

if [ "$CMD" != "get" ]; then
    exit 0;
fi

askpass
