#!/bin/bash

USERNAME="$1"
SITE="$2"

askpass() {
    printf "%s" "password=";
    echo $(python3 -c "import getpass; print(getpass.getpass())" | spectre -u"$USERNAME" -Fnone "$SITE");
}; 

if [ "$3" != "get" ]; then
    exit 0;
fi

askpass
